-- vim.opt.list = true
-- vim.opt.listchars:append "space:⋅"
-- vim.opt.listchars:append "eol:↴"

-- require('ibl').setup({
--   exclude = {
--     buftypes = { 'terminal' },
--     filetypes = { 'dashboard', 'NvimTree', 'packer', 'lsp-installer' }
--   },
--   scope = {
--     enabled = true,
--     show_end = true
--   }
-- })
